### ISSUE TITLE
Guidance around using www in links

### ISSUE THREAD

**Issue by libbyv** [AusDTO/gov-au-content-guide#216] opened 2017-01-04 23:27 UTC

**Comment by libbyv** [comment] 2017-01-04 23:28
See discussion in Content Community thread early Jan 2017

**Comment by klepas** [comment] 2017-01-08 05:57
@libbyv this might be a duplicate of #162?

**Comment by joolswood** [comment] 2017-02-17 04:24
Duplicate of https://github.com/govau/content-guide/issues/22

**Closed as completed by joolswood** 2017-02-17 04:24 UTC
